version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    groups:
      gradle-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/gradle/libs.versions.toml"
    schedule:
      interval: "weekly"
    groups:
      toml-dependencies:
        patterns:
          - "*"
